CREATE TABLE IF NOT EXISTS "customer" (
    "guid"          UUID NOT NULL,
    "first_name"    VARCHAR NOT NULL DEFAULT '',
    "last_name"     VARCHAR NOT NULL DEFAULT '',
    "created_at"    TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at"    TIMESTAMP(0) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);